branches:
  only:
  - master
  - develop
  - /^greenkeeper/.*$/
  - /^v[0-9]+\.[0-9]+\.[0-9]+/

sudo: required
language: node_js
services:
- docker

before_install:
- curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
- sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
- sudo apt-get update
- sudo apt-get -y --allow-downgrades install docker-ce=$DOCKER_VERSION
- openssl aes-256-cbc -K $encrypted_1fd173b91261_key -iv $encrypted_1fd173b91261_iv -in ci/build_args.encrypted -out ci/build_args -d
- nvm install $NODE_VERSION
- node --version

script:
- npm test
- npm run dist

after_success:
- bash <(curl -s https://codecov.io/bash)

node_js:
- '8.6'

env:
- NODE_VERSION=8.6      MARKLOGIC_VERSION=8.0-1       DOCKER_VERSION=17.06.0~ce-0~ubuntu
- NODE_VERSION=8.6      MARKLOGIC_VERSION=8.0-6.4     DOCKER_VERSION=17.09.0~ce-0~ubuntu
- NODE_VERSION=10.15.3  MARKLOGIC_VERSION=9.0-4       DOCKER_VERSION=18.06.1~ce~3-0~ubuntu
- NODE_VERSION=12.13.0  MARKLOGIC_VERSION=10.0-2.1    DOCKER_VERSION=18.06.1~ce~3-0~ubuntu

before_deploy:
- cd $TRAVIS_BUILD_DIR
- cd dist

deploy:
  - provider: npm
#    edge: true
    on:
      tags: true
      all_branches: true
      condition: $NODE_VERSION = 12.13.0 && $TRAVIS_TAG =~ ^v[0-9]+\.[0-9]+\.[0-9]+
      repo: laurelnaiad/mldock
    # src: dist
    email: laurelnaiad@gmail.com
    skip_cleanup: true
    api_key:
      secure: guurnQHJxBaZS+fe5YKNYXTUHqdDL6BLk4ETPtv7OmzJeVAmwgSMO4adaYR+5RpEEH52Dj8i0fXSz62bZXT0NJD7zv4/HdfM+aZmuGC9l0eOsEg6XyMfYo6tiQRcPX2PUq5fnGciXIji0xMLbuwcNQ+Cp6svoQDKDR4LQjhxCJdG9osWyWcqjfLYxvzUqAJmzgoN/WJRFUYSm+W7K+h9dZ0EKSKgPrVYQqaKtaCSnjMyIuAYjPaDexRT/3lefLnJ9BuYW849YnqNnh2l8R5L9aBqgs6KdQRrcxOww5g00Oa/De2OPbAxQU0yW4dLun+bIDlKZshWDqbFhXarBXvah2fDbLVtx4ePYxz7AkPZGZisDm+upmQRL3JL2NhSATnSxiW11vDIjprU62EP7Cn97mrDMD0M/zZUfzrtoMpR8tKIE2rEs3PXVnnX+zZD3lCjMNJLLXy0IwdckerrBqE1dJsW9/qTLlSg7VezIDRlqKVhV2WuzIUAluGR+em/Aht5S5X3yMIoqQvxJAqx3UckJwsLN09QZs3u2PvdBcae995w3Tui8cfPUaCS5ju90qQxrs4PB9Izb2RWxkHE3Ixgfgn8LM36Wnz+KslNt6xD3fIk6B2ZWEzdwQLJqFhujzVTvwFUZlo/CttqupQdO4MzjpxLrBwFfQ5i2UPa8NR30LY=
  # - provider: releases
  #   edge: true
  #   on:
  #     tags: true
  #     all_branches: true
  #     condition: $NODE_VERSION = 10.15.3 && $TRAVIS_TAG =~ ^v[0-9]+\.[0-9]+\.[0-9]+
  #   file: '**/*'
  #   token:
  #     secure: aR60Kg7eVZ3z1i5cT5K8vwhvUDVz9iJbOS4htOiPpfCsRUZm+viKeyrrL1/JSAawa2kCTwN7QrdWeBhTbWPt9j5PyB9YVC3Awix0C1y7vDemRMVwEeSMBB+U1LQkSHOVR96DUgeq/KrVC73DEDhX0chSsyXFZH8nnI2QOmimLwu57yXEEPM5QzF017U0W5+Kp6Ub6THvSt0EfHKGJLsTsQJqTJ3mj+cyzNthvBeGk1G2W2x/VttW6oyImCK9hotsy6Hc4JL4Kax0WURGdW3pjbt2M3QSUg7zfRswd4qtNnjghDuNp6DO8vYmNkni+sha6aKhDM0HysGDtFaNwsuz31f55P+giLhadvpnsUEnEdHeOnQ+likNFTOSI4doA0kYtxx1eG0W3EcZ+Dot2M2PSXG/CmN8f3EEXGQyEEYoQmeRYUQdSDqAb/g5S7vnM6SBDYxWaBWPgOeGwfnM5+4toKNgxWWS6xHw1LBxtTFRdxoKWR6ZA2SoDOD5JqXeyIm1ebRsD2UbXopJmoMT32cIyowPgXjhW9/sSafywpFzSPTFb7bHSDhg/2R81CnRyiUmDJ+ii+6oGwxYP3gppY2zPMPUIInR1WxDOJNe1+Ew7tdwfH69egoCfJech5Soo9Pp9yYhWFx4HMetkSW4CG3i6sAc/4YPzAJ6YKCiwpiECGg=
