branches:
  only:
  - master
  - develop
  - publish_prep
  - /^greenkeeper/.*$/
before_install:
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
  - sudo apt-get update
  - sudo apt-get -y install docker-ce=$DOCKER_VERSION
  - openssl aes-256-cbc -K $encrypted_1fd173b91261_key -iv $encrypted_1fd173b91261_iv -in ci/build_args.encrypted -out ci/build_args -d
after_success: yarn coverage
sudo: required
services:
  - docker
language: node_js
node_js:
  - "6.5"
  - "7"
env:
  - MARKLOGIC_VERSION=8.0-1     DOCKER_VERSION=17.06.0~ce-0~ubuntu
  - MARKLOGIC_VERSION=8.0-6.4   DOCKER_VERSION=17.06.0~ce-0~ubuntu
  - MARKLOGIC_VERSION=9.0-2     DOCKER_VERSION=17.06.1~ce-0~ubuntu
  - MARKLOGIC_VERSION=9.0-2     DOCKER_VERSION=17.06.1~ce-0~ubuntu
